### ISSUE TITLE
No path on the cloudkey

### ISSUE THREAD

**Issue by kelly7552** [MylesBorins/starlink-tools#1]
this is what the /usr/lib/unifi/data looks like:

drwxr-x--- 6 unifi unifi  4096 May  2 10:40 ./
drwxr-xr-x 5 root  root   4096 Aug  6  2018 ../
drwxr-x--- 3 unifi unifi  4096 May  2 08:53 backup/
drwxr-x--- 4 unifi unifi  4096 May  2 09:35 db/
-rw-r----- 1 unifi unifi 45983 May  2 09:38 firmware.json
lrwxrwxrwx 1 unifi unifi    35 Aug  6  2018 keystore -> /etc/ssl/private/unifi.keystore.jks
-rw-r----- 1 unifi unifi  1424 May  2 09:35 model_lifecycles.json
-rw-r----- 1 unifi unifi     0 May  2 09:38 system.configured
-rw-r----- 1 unifi unifi  1361 May  2 09:38 system.properties
-rw-r----- 1 unifi unifi  1361 May  2 09:38 system.properties.bk
drwxr-x--- 3 unifi unifi  4096 May  2 09:34 tmp/
drwxr-x--- 3 unifi unifi  4096 May  2 10:40 webrtc/

I don't see anywhere to place the config.gateway.json file

**Comment by MylesBorins** [comment]
you may need to

```
mkdir -p /usr/lib/unifi/data/sites/default
```

first

**Comment by kelly7552** [comment]
Thanks!  I did that, any way to know if it's working?

**Comment by MylesBorins** [comment]
If the provision of the secure gateway worked you should be able to check the logs on the device by ssh'ing into it
